export default {
  /**
   * Public url of the application
   * This is used to prefix the links of assets generated by build process. This can be set to "/" when the website
   * is hosted on rooted domain
   */
  publicUrl: process.env.PUBLIC_URL,
  /**
   * Application environment
   */
  appEnv: process.env.NODE_ENV,
  /**
   * Application domain url
   */
  appUrl: process.env.APP_URL,
  /**
   * Version of the application
   */
  appVersion: process.env.REACT_APP_VERSION,
  /**
   * Name of the applications
   */
  appName: process.env.REACT_APP_APPLICATION_NAME,
  /**
   * Base url for the server
   */
  serverBase: process.env.REACT_APP_SERVER_BASE,
  /**
   * Base url for the apis
   */
  apiBaseUrl: process.env.REACT_APP_API_BASE_URL,
  /**
   * Pusher configuration
   */
  pusher: {
    key: process.env.REACT_APP_PUSHER_APP_KEY,
    cluster: process.env.REACT_APP_PUSHER_APP_CLUSTER || "ap2",
    authEndpoint: process.env.REACT_APP_SERVER_BASE + "/broadcasting/auth",
  },
}
